let concentrationChart = null;
let patientData = {};
function $(id){return document.getElementById(id);}
function fmt(n,d=1){return Number.isFinite(Number(n))?Number(n).toFixed(d):'N/A';}
function getInfusionTime(doseMg){return VancoEngine.getInfusionTimeHours(doseMg);} // hours, ≤10 mg/min

document.addEventListener('DOMContentLoaded', function(){ initializeChart(); setupEventListeners(); updatePatientSummary(); });
function setupEventListeners(){ document.querySelectorAll('input, select').forEach(input=>{input.addEventListener('input',updatePatientSummary); input.addEventListener('change',updatePatientSummary);}); }
function resetForm(){ if(confirm('คุณต้องการล้างข้อมูลทั้งหมดใช่หรือไม่?')){ document.querySelectorAll('input[type="number"]').forEach(input=>{ if(input.id==='targetAUC') input.value='500'; else if(input.id==='peakTime') input.value='1'; else input.value=''; }); document.querySelectorAll('input[type="checkbox"]').forEach(c=>c.checked=false); $('gender').value='male'; $('interval').value='12'; clearResults(); updatePatientSummary(); clearChart(); showAlert('ข้อมูลถูกล้างเรียบร้อยแล้ว','info'); }}
function getPatientInput(){ return { weight:parseFloat($('weight').value), height:parseFloat($('height').value), age:parseFloat($('age').value), sex:$('gender').value, scr:parseFloat($('scr').value), dialysis:$('dialysis')?$('dialysis').checked:false, criticallyIll:$('criticallyIll')?$('criticallyIll').checked:false, mic:1 }; }
function updatePatientSummary(){ const raw=getPatientInput(); const summary=$('patientSummary'); if(raw.weight&&raw.height&&raw.age&&raw.scr){ const p=VancoEngine.enrichPatient(raw); patientData={ weight:p.weight,height:p.height,age:p.age,gender:p.sex,scr:p.scr,bmi:p.bmi,bsa:p.bsa,ibw:p.ibw,abw:p.adjbw,crCl:p.crcl,dialysis:p.dialysis,criticallyIll:p.criticallyIll}; const m=VancoEngine.selectModel(p); const pk=m.one(p); summary.innerHTML=`<div class="space-y-3"><div class="grid grid-cols-2 gap-3"><div><strong>BMI:</strong> ${fmt(p.bmi,1)}</div><div><strong>BSA:</strong> ${fmt(p.bsa,2)} m²</div><div><strong>IBW:</strong> ${fmt(p.ibw,1)} kg</div><div><strong>AdjBW:</strong> ${fmt(p.adjbw,1)} kg</div><div><strong>CrCl:</strong> ${fmt(p.crcl,1)} mL/min</div><div><strong>Model:</strong> ${m.name}</div><div><strong>CL:</strong> ${fmt(pk.cl,2)} L/hr</div><div><strong>Vd:</strong> ${fmt(pk.vd,1)} L</div></div>${p.bmi>=30?'<div class="p-3 bg-yellow-50 border border-yellow-200 rounded-lg text-yellow-800 text-xs"><i class="fas fa-exclamation-triangle mr-1"></i>ผู้ป่วยอ้วน: ใช้ population model ที่เหมาะสมและติดตาม TDM</div>':''}${p.crcl>130?'<div class="p-3 bg-orange-50 border border-orange-200 rounded-lg text-orange-800 text-xs"><i class="fas fa-bolt mr-1"></i>Augmented renal clearance: ควรติดตามระดับยาเร็วขึ้น</div>':''}${p.dialysis?'<div class="p-3 bg-red-50 border border-red-200 rounded-lg text-red-800 text-xs"><i class="fas fa-exclamation-triangle mr-1"></i>RRT/HD: ใช้ protocol เฉพาะและ dose by level</div>':''}</div>`; } else { patientData={}; summary.innerHTML='<div class="text-center py-8 text-gray-400"><i class="fas fa-user-plus text-4xl mb-3"></i><p>กรอกข้อมูลผู้ป่วยเพื่อแสดงสรุป</p></div>'; }}
function validatePatientData(){ const required=['weight','height','age','scr']; for(const f of required){ const value=parseFloat($(f).value); if(!value||value<=0){ showAlert(`กรุณากรอกข้อมูล${getFieldName(f)}`,'error'); $(f).focus(); return false; }} return true; }
function validateTDMData(){ if(!validatePatientData()) return false; const required=['currentDose','troughLevel','troughTime']; for(const f of required){ const value=parseFloat($(f).value); if(!value||value<=0){ showAlert(`กรุณากรอกข้อมูล${getFieldName(f)}`,'error'); $(f).focus(); return false; }} const peak=parseFloat($('peakLevel').value), trough=parseFloat($('troughLevel').value); if(Number.isFinite(peak) && peak<=trough){ showAlert('Peak ต้องมากกว่า trough','error'); return false;} return true; }
function getFieldName(field){ return ({weight:'น้ำหนัก',height:'ส่วนสูง',age:'อายุ',scr:'SCr',currentDose:'ขนาดยาปัจจุบัน',peakLevel:'Peak Level',troughLevel:'Trough Level',troughTime:'Trough Time'})[field]||field; }
function estimateFromForm(requireDose=true){ if(requireDose && !validateTDMData()) return null; if(!requireDose && !validatePatientData()) return null; const raw=getPatientInput(); const patient=VancoEngine.enrichPatient(raw); const dose=parseFloat($('currentDose').value)||1000; const interval=parseFloat($('interval').value)||12; const targetAUC=parseFloat($('targetAUC').value)||500; const peak=parseFloat($('peakLevel').value); const trough=parseFloat($('troughLevel').value); const peakTime=parseFloat($('peakTime').value); const troughTime=parseFloat($('troughTime').value)||interval; const method=(Number.isFinite(peak)||Number.isFinite(trough))?'bayesian':'population'; const est=VancoEngine.estimatePk({patient,dose,interval,peak,trough,peakTime,troughTime,method,priorConfidence:'medium'}); if(est.error) showAlert(est.error,'warning'); return {patient,dose,interval,targetAUC,peak,trough,peakTime,troughTime,est,pk:est.finalPk}; }
function calculateInitialDose(){ if(!validatePatientData()) return; clearResults(); const patient=VancoEngine.enrichPatient(getPatientInput()); const targetAUC=parseFloat($('targetAUC').value)||500; const model=VancoEngine.selectModel(patient); const pk=model.one(patient); const interval=parseFloat($('interval').value)||VancoEngine.recommendMaintenance({patient,targetAUC,pk}).interval; const rec=VancoEngine.recommendMaintenance({patient,targetAUC,interval,pk}); const pred=VancoEngine.predictedPeakTrough(rec.dose,rec.interval,pk); const result={dose:rec.dose,interval:rec.interval,auc24:rec.auc,clearance:pk.cl,vd:pk.vd,ke:pk.cl/pk.vd,halfLife:0.693/(pk.cl/pk.vd),expectedPeak:pred.peak,expectedTrough:pred.trough,model:model.name}; displayInitialDoseResult(result); updateChart({dose:rec.dose,interval:rec.interval,clearance:pk.cl,vd:pk.vd}); }
function calculateAUC(){ const inp=estimateFromForm(true); if(!inp) return; clearResults(); const auc24=VancoEngine.auc24(inp.dose,inp.interval,inp.pk.cl); const pred=VancoEngine.predictedPeakTrough(inp.dose,inp.interval,inp.pk); const result={auc:auc24/24*inp.interval,auc24,ke:inp.pk.cl/inp.pk.vd,vd:inp.pk.vd,halfLife:0.693/(inp.pk.cl/inp.pk.vd),clearance:inp.pk.cl,cTruePeak:pred.truePeak,cTrueTrough:pred.trough,tin:pred.tin,tau:inp.interval,dose:inp.dose,model:inp.pk.model,usedBayesian:inp.est.usedBayesian}; displayAUCResult(result); updateChart({dose:inp.dose,interval:inp.interval,clearance:inp.pk.cl,vd:inp.pk.vd}); }
function adjustDose(){ const inp=estimateFromForm(true); if(!inp) return; const currentAUC=VancoEngine.auc24(inp.dose,inp.interval,inp.pk.cl); const adj=VancoEngine.adjustDose({currentDose:inp.dose,interval:inp.interval,currentAUC,targetAUC:inp.targetAUC}); const result={currentDose:inp.dose,newDose:adj.newDose,percentChange:adj.percentChange,currentAUC24:currentAUC,targetAUC:inp.targetAUC,halfLife:0.693/(inp.pk.cl/inp.pk.vd)}; displayDoseAdjustmentResult(result); updateChart({dose:adj.newDose,interval:inp.interval,clearance:inp.pk.cl,vd:inp.pk.vd}); }
function calculateLoadingDose(){ if(!validatePatientData()) return; clearResults(); const patient=VancoEngine.enrichPatient(getPatientInput()); const ld=VancoEngine.recommendLoading(patient,patient.criticallyIll?'severe':'normal'); const result={loadingDose:ld.dose,weight:patient.weight,factor:ld.mgkg,isObese:patient.bmi>=30,infusionMinutes:ld.infusionMinutes}; displayLoadingDoseResult(result); showAlert(`Infusion time ที่แนะนำ: อย่างน้อย ${ld.infusionMinutes} นาที (≤10 mg/min)`,'info'); }
function displayInitialDoseResult(result){ const html=`<div class="result-card rounded-xl p-6 shadow-lg"><h3 class="text-xl font-semibold mb-4 flex items-center"><i class="fas fa-prescription-bottle mr-2"></i>ขนาดยาเริ่มต้นที่แนะนำ</h3><div class="text-center mb-4"><div class="text-4xl font-bold">${result.dose}</div><div class="text-lg opacity-90">mg ทุก ${result.interval} ชั่วโมง</div></div><div class="grid grid-cols-2 gap-4 text-sm bg-white bg-opacity-20 rounded-lg p-3"><div><strong>AUC24:</strong> ${fmt(result.auc24,0)}</div><div><strong>Model:</strong> ${result.model}</div><div><strong>Peak คาด:</strong> ${fmt(result.expectedPeak,1)}</div><div><strong>Trough คาด:</strong> ${fmt(result.expectedTrough,1)}</div><div><strong>CL:</strong> ${fmt(result.clearance,2)} L/hr</div><div><strong>Half-life:</strong> ${fmt(result.halfLife,1)} hr</div></div>${getAUCRecommendation(result.auc24,500)}</div>`; $('resultsContainer').innerHTML=html; }
function displayAUCResult(result){ const html=`<div class="success-card rounded-xl p-6 shadow-lg"><h3 class="text-xl font-semibold mb-4 flex items-center"><i class="fas fa-chart-area mr-2"></i>ผลการคำนวณ AUC ${result.usedBayesian?'<span class="ml-auto text-xs bg-blue-500 px-2 py-1 rounded-full">Bayesian/MAP</span>':''}</h3><div class="grid grid-cols-2 gap-4 text-sm bg-white bg-opacity-20 rounded-lg p-3"><div><strong>AUC24:</strong> ${fmt(result.auc24,0)} mg·h/L</div><div><strong>Model:</strong> ${result.model||'Population'}</div><div><strong>CL:</strong> ${fmt(result.clearance,2)} L/hr</div><div><strong>Vd:</strong> ${fmt(result.vd,1)} L</div><div><strong>Ke:</strong> ${fmt(result.ke,4)} hr⁻¹</div><div><strong>Half-life:</strong> ${fmt(result.halfLife,1)} hr</div><div><strong>Pred Peak:</strong> ${fmt(result.cTruePeak,1)}</div><div><strong>Pred Trough:</strong> ${fmt(result.cTrueTrough,1)}</div></div>${getAUCRecommendation(result.auc24,500)}</div>`; $('resultsContainer').innerHTML=html; }
function displayDoseAdjustmentResult(result){ const status=Math.abs(result.percentChange)<=10?'success':'info'; const html=`<div class="${status}-card rounded-xl p-6 shadow-lg"><h3 class="text-xl font-semibold mb-4 flex items-center"><i class="fas fa-adjust mr-2"></i>การปรับขนาดยา</h3><div class="grid grid-cols-2 gap-4 mb-4"><div class="text-center"><div class="text-sm opacity-90">ปัจจุบัน</div><div class="text-2xl font-bold">${result.currentDose} mg</div><div class="text-sm">AUC24: ${fmt(result.currentAUC24,0)}</div></div><div class="text-center"><div class="text-sm opacity-90">แนะนำ</div><div class="text-2xl font-bold text-yellow-300">${result.newDose} mg</div><div class="text-sm">Target: ${result.targetAUC}</div></div></div><div class="text-center mb-4"><div class="text-lg">การเปลี่ยนแปลง: <span class="font-bold ${result.percentChange>0?'text-green-300':'text-red-300'}">${result.percentChange>0?'+':''}${fmt(result.percentChange,1)}%</span></div></div><div class="bg-white bg-opacity-20 rounded-lg p-3 text-sm"><div class="font-medium mb-2">คำแนะนำ:</div>${getDoseAdjustmentRecommendation(result)}</div></div>`; $('resultsContainer').innerHTML=html; }
function displayLoadingDoseResult(result){ const html=`<div class="info-card rounded-xl p-6 shadow-lg"><h3 class="text-xl font-semibold mb-4 flex items-center"><i class="fas fa-bolt mr-2"></i>Loading Dose</h3><div class="text-center mb-4"><div class="text-4xl font-bold">${result.loadingDose}</div><div class="text-lg opacity-90">mg</div></div><div class="text-sm space-y-2 bg-white bg-opacity-20 rounded-lg p-3"><div class="flex justify-between"><span>น้ำหนักที่ใช้คำนวณ:</span><span>${fmt(result.weight,1)} kg (${result.isObese?'TBW capped':'TBW'})</span></div><div class="flex justify-between"><span>Factor:</span><span>${result.factor} mg/kg</span></div><div class="flex justify-between"><span>Infusion time:</span><span>≥ ${result.infusionMinutes} min</span></div></div><div class="mt-4 p-3 bg-yellow-500 bg-opacity-20 rounded-lg text-sm"><i class="fas fa-exclamation-triangle mr-2"></i><strong>หมายเหตุ:</strong> ให้ Loading dose ครั้งเดียว จากนั้นเริ่ม maintenance dose ตาม interval ที่เหมาะสม</div></div>`; $('resultsContainer').innerHTML=html; }
function initializeChart(){ const canvas=$('concentrationChart'); if(!canvas||typeof Chart==='undefined') return; concentrationChart=new Chart(canvas.getContext('2d'),{type:'line',data:{labels:[],datasets:[{label:'Vancomycin Concentration',data:[],borderColor:'rgb(75, 192, 192)',backgroundColor:'rgba(75, 192, 192, 0.1)',tension:0.4,fill:true}]},options:{responsive:true,maintainAspectRatio:false,plugins:{title:{display:true,text:'Vancomycin Concentration vs Time'},legend:{display:true}},scales:{x:{title:{display:true,text:'Time (hours)'}},y:{title:{display:true,text:'Concentration (mcg/mL)'},beginAtZero:true}}}}); }
function updateChart(result){ if(!concentrationChart) return; const dose=result&&result.dose?result.dose:1000; const tau=result&&result.interval?result.interval:12; const cl=result&&result.clearance?result.clearance:5; const vd=result&&result.vd?result.vd:(cl/0.08); const pts=VancoEngine.buildProfile(dose,tau,{cl,vd},tau*2,0.25); concentrationChart.data.labels=pts.map(p=>p.time); concentrationChart.data.datasets[0].data=pts.map(p=>p.conc); concentrationChart.update(); }
function updateChartFromTDM(result){ updateChart(result); }
function clearChart(){ if(!concentrationChart) return; concentrationChart.data.labels=[]; concentrationChart.data.datasets[0].data=[]; concentrationChart.update(); }
function getAUCRecommendation(auc24,target=500){ if(auc24<400) return `<div class="mt-3 p-3 bg-red-500 bg-opacity-20 rounded-lg"><i class="fas fa-arrow-up mr-2"></i><strong>แนะนำ:</strong> เพิ่มขนาดยาหรือลดระยะห่างการให้ยา และติดตามระดับยา</div>`; else if(auc24>600) return `<div class="mt-3 p-3 bg-orange-500 bg-opacity-20 rounded-lg"><i class="fas fa-arrow-down mr-2"></i><strong>แนะนำ:</strong> ลดขนาดยาหรือเพิ่มระยะห่างการให้ยา เนื่องจาก AUC >600</div>`; return `<div class="mt-3 p-3 bg-green-500 bg-opacity-20 rounded-lg"><i class="fas fa-check mr-2"></i><strong>สถานะ:</strong> AUC อยู่ในช่วงเป้าหมาย 400–600</div>`; }
function getDoseAdjustmentRecommendation(result){ if(result.currentAUC24>650) return 'AUC สูงมาก ควรพิจารณาหยุด/เลื่อน dose ถัดไปและตรวจระดับยา/SCr ซ้ำ'; if(Math.abs(result.percentChange)<=10) return 'ขนาดยาปัจจุบันเหมาะสม ไม่จำเป็นต้องปรับ'; if(Math.abs(result.percentChange)>50) return 'การเปลี่ยนแปลงขนาดยามาก ควรยืนยันข้อมูลเวลาเจาะเลือดและติดตาม TDM อย่างใกล้ชิด'; return `ปรับขนาดยาจาก ${result.currentDose} mg เป็น ${result.newDose} mg และติดตาม TDM ตามความเสี่ยง`; }
function showAlert(message,type='info'){ const alertClass={'success':'bg-green-100 border-green-400 text-green-700','error':'bg-red-100 border-red-400 text-red-700','warning':'bg-yellow-100 border-yellow-400 text-yellow-700','info':'bg-blue-100 border-blue-400 text-blue-700'}; const iconClass={'success':'fas fa-check-circle','error':'fas fa-exclamation-triangle','warning':'fas fa-exclamation-triangle','info':'fas fa-info-circle'}; const alert=document.createElement('div'); alert.className=`${alertClass[type]||alertClass.info} border px-4 py-3 rounded-lg mb-4 flex items-center`; alert.innerHTML=`<i class="${iconClass[type]||iconClass.info} mr-2"></i><span>${message}</span><button onclick="this.parentElement.remove()" class="ml-auto"><i class="fas fa-times"></i></button>`; $('alerts').appendChild(alert); setTimeout(()=>{ if(alert.parentElement) alert.remove(); },7000); }
function clearResults(){ $('resultsContainer').innerHTML=''; }
function printResults(){ window.print(); }
